version: '3'
services:
  redis:
    image: redis:alpine

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile-local
    environment:
      - ENV_REDIS_HOST="redis:6379"
    depends_on:
      - redis
    ports:
      - 1337:1337
    
