version: '3'

networks:
  internal:
    driver: bridge

services:
  redis:
    # Use the official image for Redis with ReJSON support.
    image: redis/redis-stack:latest
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    ports:
      - 6379:6379
      - 8001:8001
    networks: 
      - internal

  backend:
    build:
      # Context is . because we need the protos folder for now.
      context: .
      dockerfile: ./backend/Dockerfile-local-debug
    environment:
      - COLABSHIELD_PORT=1337
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    depends_on:
      - redis
    ports:
      - 1337:1337
      - 2345:2345
    networks:
      - internal
