# Start with a base image
FROM golang:1.22-alpine

# Define the default values for the build arguments
ARG ARG_PORT=1337
ARG ARG_REDIS_HOST="redis"
ARG ARG_REDIS_PORT=6379
ARG ARG_REDIS_PASSWORD="redis"
ARG ARG_DELVE_PORT=2345

# Set the working directory inside the container to match
# the workspace directory in the devcontainer
WORKDIR /workspaces/colab-shield

# Add delve for debugging
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Copy the source code into the container
COPY ./backend ./backend

#TODO: Only for dev purposes and should be removed.
COPY ./protos ./protos 

# Download the Go module dependencies
RUN cd backend && go mod download

# Build the Go application
RUN cd backend && go build .

ENV COLABSHIELD_GRPC_PORT=$ARG_PORT
ENV REDIS_HOST=$ARG_REDIS_HOST
ENV REDIS_PORT=$ARG_REDIS_PORT
ENV REDIS_PASSWORD=$ARG_REDIS_PASSWORD
ENV DELVE_PORT=$ARG_DELVE_PORT

EXPOSE $PORT
EXPOSE 2345

# Deliberately using shell form of entry point to allow for environment variable substitution
ENTRYPOINT dlv --continue --accept-multiclient --listen=:$DELVE_PORT --headless=true --api-version=2 --log exec ./backend/backend

